'use strict';
/** node test/font-ship.test.js — 삼국지 R15: 새 동봉 글꼴이 라이트 업데이트로 설치본에 가고, 선언했는데 파일이 없으면 알린다 */
const fs = require('fs'), path = require('path'), os = require('os');
const { missingBundledFonts, BUNDLED_FACES, bundledFontCss } = require('../core/book/pdf-builder');
let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log('  ✓ ' + m); } else { fail++; console.log('  ✗ ' + m); } };
const src = fs.readFileSync(path.join(__dirname, '..', 'scripts', 'gen-manifest.js'), 'utf8');
const m = src.match(/EXCLUDE_REL = \[([\s\S]*?)\n\];/)[1].match(/^\s*(\/\^assets\\\/fonts\\\/book[^\n]*?\/),/m);
const re = eval(m[1]);
const shipped = (f) => !re.test('assets/fonts/book/' + f);
console.log('\n[1] 매니페스트 규칙');
for (const f of ['NotoSerifKR-Light.ttf', 'NotoSerifKR-OFL.txt', 'HanjaSerif-Light.ttf', 'HanjaSerif-OFL.txt']) ok(shipped(f), `${f} 배포`);
for (const f of ['KoPubWorld-Batang-Light.ttf', 'NanumMyeongjo-Regular.ttf', 'NanumGothic-Bold.ttf']) ok(!shipped(f), `${f} 제외(설치본에 이미 있음)`);
ok(BUNDLED_FACES.filter(([, f]) => /^(NotoSerifKR|HanjaSerif)-/.test(f)).every(([, f]) => shipped(f)), '선언된 새 글꼴 파일은 전부 배포 대상(판별: 선언표 ↔ 규칙)');
console.log('\n[2] 누락 점검');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fnt-'));
ok(missingBundledFonts(dir).length === BUNDLED_FACES.length, '빈 폴더 → 선언 전부 누락');
fs.writeFileSync(path.join(dir, 'HanjaSerif-Light.ttf'), 'x');
const miss = missingBundledFonts(dir);
ok(miss.length === BUNDLED_FACES.length - 1 && !miss.includes('HanjaSerif-Light.ttf'), '파일 하나 두면 그것만 빠짐');
fs.rmSync(dir, { recursive: true, force: true });
ok(missingBundledFonts().length === 0, '개발 폴더엔 선언 파일이 전부 있다');
const mf = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'update-manifest.json'), 'utf8')).files;
console.log('\n[3] 실제 매니페스트(update:publish 뒤)');
for (const f of ['NotoSerifKR-Light.ttf', 'HanjaSerif-Light.ttf', 'NotoSerifKR-OFL.txt', 'HanjaSerif-OFL.txt']) ok(!!mf['assets/fonts/book/' + f], `매니페스트에 ${f}`);
ok(!Object.keys(mf).some((k) => /fonts\/book\/(KoPub|Nanum)/.test(k)), '매니페스트에 KoPub·나눔 없음');
ok(bundledFontCss().includes('Priming Hanja Serif'), '@font-face 가 같은 표에서 나온다');
const M = fs.readFileSync(path.join(__dirname, '..', 'main.js'), 'utf8');
ok((M.match(/warnMissingFontFiles\('/g) || []).length === 2 && /동봉 글꼴 파일 없음/.test(M), 'main: 미리보기·내지 PDF 두 곳에서 경고');
ok(/글꼴 확인 불완전/.test(M), 'main: 못 읽은 글꼴이 있으면 「누락 0」 대신 알림');
console.log(`\n${fail ? '❌' : '✅'} font-ship — ${pass} 통과 / ${fail} 실패`);
process.exit(fail ? 1 : 0);
